name: library_management
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  mongo_dart: ^0.10.5
  json_annotation: ^4.9.0
  flutter_svg: ^2.2.1
  shared_preferences: ^2.5.3
  carousel_slider: ^5.1.1
  dropdown_button2: ^2.3.9
  intl: ^0.20.2
  fl_chart: ^0.69.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
